name: Workflow Dispatcha

on:
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: true
        default: "World"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello ${{ github.event.inputs.input }}
